### ISSUE TITLE
Unable to pass variables to the tag

### ISSUE THREAD

**Issue by Cardridge** [rcmdnk/octopress-thumbnail#1]
Is it possible to pass variables to the thumbnailer? I'm currently generating a rather big gallery and would prefer not having to add every single path to the page.

Here's what I'm trying to do:

```
{% for folder in site.data.gallery %}

  <h3>{{ folder.title }}</h3>

  {% for i in (1..folder.imagecount) %}
  {% capture original %}/img/gallery/{{ folder.index }}-{{ folder.foldername }}/{{ forloop.index0 }}.jpg{% endcapture %}

  <a href="{{ original | prepend: site.baseurl }}">
    {% thumbnail original 140 140 %}
  </a>

  {% endfor %}

{% endfor %}
```

This script seems to be picking up the value "original" as a name or something, not the captured string.

**Comment by rcmdnk** [comment]
You can do it by using `val:` like:

    <a href="{{ original | prepend: site.baseurl }}">
      {% thumbnail val:original 140 140 %}
    </a>

If `val:` is added, the plugin treat it as a variable.

It was not documented, sorry. I have updated the document.

**Comment by Cardridge** [comment]
Passing `val:` does work. Now I'm getting this error, not sure if it's related to this plugin or how jekyll handles the process.
```jekyll 3.3.1 | Error:  File name too long @ rb_file_s_stat - /home/user/project/img/gallery/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/thumbnail/0_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140_140.jpg```

**Comment by rcmdnk** [comment]
hmm... what is written in _config.yml for site.data.gallery?

I tested with following _config.yml:

    data:
      gallery:
        - a:
          title: title_a
          index: 1
          imagecount: 5
          foldername: folder_a
        - b:
          title: title_b
          index: 2
          imagecount: 3
          foldername: folder_3

and in post:

    {% for folder in site.data.gallery %}
      <h3>{{ folder.title }}</h3>
      {% for i in (1..folder.imagecount) %}
      {% capture original %}/img/gallery/{{ folder.index }}-{{ folder.foldername }}/{{ forloop.index0 }}.jpg{% endcapture %}
      <a href="{{ original | prepend: site.baseurl }}">
        {% thumbnail val:original 140 140 %}
      </a>
      {% endfor %}
    {% endfor %}

then I got html like:

    <h3>title_a</h3>

    <p><a href="/img/gallery/1-folder_a/0.jpg">
        <img src="/images/img/gallery/1-folder_a/0.jpg" width="140" height="140" />
      </a></p>

    <p><a href="/img/gallery/1-folder_a/1.jpg">
        <img src="/images/img/gallery/1-folder_a/0.jpg" width="140" height="140" />
      </a></p>

    <p><a href="/img/gallery/1-folder_a/2.jpg">
        <img src="/images/img/gallery/1-folder_a/0.jpg" width="140" height="140" />
      </a></p>

    <p><a href="/img/gallery/1-folder_a/3.jpg">
        <img src="/images/img/gallery/1-folder_a/0.jpg" width="140" height="140" />
      </a></p>

    <p><a href="/img/gallery/1-folder_a/4.jpg">
        <img src="/images/img/gallery/1-folder_a/0.jpg" width="140" height="140" />
      </a></p>

    <h3>title_b</h3>

    <p><a href="/img/gallery/2-folder_3/0.jpg">
        <img src="/images/img/gallery/1-folder_a/0.jpg" width="140" height="140" />
      </a></p>

    <p><a href="/img/gallery/2-folder_3/1.jpg">
        <img src="/images/img/gallery/1-folder_a/0.jpg" width="140" height="140" />
      </a></p>

    <p><a href="/img/gallery/2-folder_3/2.jpg">
        <img src="/images/img/gallery/1-folder_a/0.jpg" width="140" height="140" />
      </a></p>

**Comment by Cardridge** [comment]
I'm using a seperate `gallery.yml` file that sits in `_data/`.

This is the censored version:

```
- index: 5
  imagecount: 4
  foldername: folder-one
  title: 'Folder One'

- index: 0
  imagecount: 5
  foldername: 'folder-two'
  title: 'Folder Two'

- index: 1
  imagecount: 1
  foldername: 'folder-three'
  title: 'Folder Three'

- index: 2
  imagecount: 3
  foldername: 'folder-four'
  title: 'Folder Four'

- index: 3
  imagecount: 14
  foldername: 'folder-five'
  title: 'Folder Five'

- index: 4
  imagecount: 5
  foldername: 'folder-six'
  title: 'Folder Six'
```

**Comment by Cardridge** [comment]
Suprisingly enough when printing the gallery using only the value original, ie.

```
  <a href="{{ original | prepend: site.baseurl }}">
    {{ original }}
  </a>
```
it will insert the urls correctly.

**Comment by rcmdnk** [comment]
ok, I fixed the problem.
(above my output also includes bad outputs..., all lines are 0.jpg)

Could you please try the latest master's one?

**Comment by Cardridge** [comment]
It works now. Thank you.
